#!/usr/bin/env bash
# a Bash script that displays Best School 10 times using until.
i=1
while ((i <= 100))
do
    if ((i % 15 == 0))
    then
        echo "FizzBuzz"
    elif ((i % 5 == 0))
    then
        echo "Buzz"
    elif ((i % 3 == 0))
    then
        echo "Fizz"
    else
        echo $i
    fi 
    i=$((i + 1))
done
