#!/usr/bin/env bash
# a Bash script that displays Best School 10 times using until.
i=1
while ((i <= 10))
do
    if ((i == 10))
    then
        echo "Hi"
    fi      
    echo "Best School"
    i=$((i + 1))
done
