#!/usr/bin/env bash
# a Bash script that displays Best School 10 times using until.
i=1
j=0
while ((j <= 12))
do  
    echo "Hour: $j"
    while ((i <= 59))
    do
        echo "$i"
        i=$((i + 1))
    done
    i=1
    j=$((j + 1))
done
